### ISSUE TITLE
Maybe toString gives away internals

### ISSUE THREAD

**Issue by arcseldon** [ramda/ramda-fantasy#100]
No big deal, but perhaps worth raising here.

Noticed the toString on Maybe is displaying _Just rather than Just. Haven't checked other Types to see if they exhibit the same behaviour. It would be cleaner if it returned a toString of what the user is workiing with - Just and Nothing in this case.

```js
const nestedIceCream = Maybe(Maybe('Ice cream'));
console.log(nestedIceCream);
// _Just { value: _Just { value: 'Ice cream' } }
```

Thoughts?

**Comment by buzzdecafe** [comment]
yeah i've seen that before and i agree it is not great. we could solve this by simply renaming `_Just` and `_Nothing` to `Just` and `Nothing` respectively, and that oughta just work.

**Comment by arcseldon** [comment]
@buzzdecafe - ok, thanks for clarification, wasn't 100% sure if it was intentional / something for which no need to fix.

Would you like me to have a go and raise PR? :smile:

**Comment by buzzdecafe** [comment]
i just did it

**Comment by arcseldon** [comment]
:+1:   thank you.

**Comment by arcseldon** [comment]
Shall i close the issue, or best to keep open until a release is made?

**Comment by buzzdecafe** [comment]
if the pr gets merged it will close this issue automatically. See: https://help.github.com/articles/closing-issues-via-commit-messages/#closing-an-issue-in-the-same-repository

**Comment by arcseldon** [comment]
Sure.

**Comment by davidchambers** [comment]
To clarify, this relates to `inspect` rather than `toString`:

```javascript
> function Foo(x) { this.value = x; }
undefined
> new Foo(42)
Foo { value: 42 }
> Foo.prototype.toString = function() { return 'Foo#toString'; }
[Function]
> new Foo(42)
Foo { value: 42 }
> Foo.prototype.inspect = function() { return 'Foo#inspect'; }
[Function]
> new Foo(42)
Foo#inspect
```

On a related note, we should add `inspect` methods to our types as we did in plaid/sanctuary#122.

**Comment by buzzdecafe** [comment]
> we should add `inspect` methods to our types

ok by me
