### ISSUE TITLE
_nothing may leak, get mutated

### ISSUE THREAD

**Issue by buzzdecafe** [ramda/ramda-fantasy#102]
```js
var n = Maybe.Nothing();
n.x = "mutated";
Maybe.Nothing().x; // "mutated"
```

this seems bad. I think we should rethink how `Nothing` is implemented. It relies too much upon the good behavior of the developer.

**Comment by TheLudd** [comment]
I can see why nothing is especially vulnerable here since there is only ever one instance. But nothing in the ramda world is protected against this kind of behavior right? Not even stuff returned by `R.always` as discussed some time ago. 

So why take precaution here when we don't do it otherwise?

**Comment by buzzdecafe** [comment]
> why take precaution here

because there is no benefit to keeping this implementation when we can get some level of enforcement with a better implementation.

**Comment by TheLudd** [comment]
I understand that it is an improvement. I just find it very inconsistent with everything else. Is it not confusing that immutability is guaranteed here but not elsewhere?

**Comment by buzzdecafe** [comment]
i guess i would say that anywhere we can get good behavior cheaply we should take advantage of.
