### ISSUE TITLE
Bower reference Ramda versioning

### ISSUE THREAD

**Issue by robjens** [ramda/ramda-fantasy#106]
The `package.json` shows a version range up to `0.20` but `bower.json` is fixed at `0.14`. ?
Is there a particular reason holding back the dependency for bower RF to be in line with `0.19.x` Ramda?

```
Unable to find a suitable version for ramda, please choose one:
    1) ramda#^0.14.0 which resolved to 0.14.0 and is required by ramda-fantasy#0.4.1
    2) ramda#^0.19.1 which resolved to 0.19.1 and is required by my-project
```

Cheers

**Comment by buzzdecafe** [comment]
no reason, just a miss

**Comment by robjens** [comment]
Ah, good. Or at least that was what I was hoping for. Lightning fast response by the way,  would an minor update be this fast as well? :)

**Comment by buzzdecafe** [comment]
i'd be grateful for a PR :-)

**Comment by robjens** [comment]
Ok sure... As I assume there won't be any/much conflicts. Just have to see if bower supports ranges as well and try it out locally first, then do a PR. This might require a new tagged release though, I'm not really sure but bower seems to kick-off on that, you happen to know? Anyway you can use the SHA to install a latest master commit as well, as opposed to tagged (snapshots) so we'll see.

**Comment by buzzdecafe** [comment]
> As I assume there won't be any/much conflicts. 

probably a risky assumption, since ramda is still pre-1.0 and has undegones a lot of api changes in that span. ramda 0.9.1 was added as a dependency here: https://github.com/ramda/ramda-fantasy/commit/1ad9f7fe7de314f8bb6f1dfe10f60667e4507660 

probably not safe to rely on anything before that at least

**Comment by robjens** [comment]
Oh.. my bad. I hadn't realized that part, actually missed the dependency range in package.json. Sorry.
