### ISSUE TITLE
Either.either not in latest release

### ISSUE THREAD

**Issue by joseaquino** [ramda/ramda-fantasy#108]
I was wondering if this is an issue or not, but the documentation shows the use of Either.either but this method is not included in the latest release (0.4.1) even though the commit for this addition is from 2015, I'm just wondering if you could add this to the release because I downloaded via NPM and trying to use it found out it is not available in the latest tagged release only in the master.

**Comment by scott-christopher** [comment]
Yep sorry about that, we're a bit overdue for a release. I'll get something up shortly.

**Comment by scott-christopher** [comment]
`0.5.0` should be available now.

**Comment by joseaquino** [comment]
Thank you @scott-christopher for the quick update. Cheers!

**Comment by CrossEye** [comment]
Wow, quick work, @scott-christopher!  Thanks.
