### ISSUE TITLE
Maybe#map

### ISSUE THREAD

**Issue by Schniz** [ramda/ramda-fantasy#114]
Hey there.

In [Chapter 8 in @DrBoolean's book](https://drboolean.gitbooks.io/mostly-adequate-guide/content/ch8.html), it is told about Maybe:

```js
Maybe.of({
  name: 'Boris',
}).map(_.prop('age')).map(add(10));
//=> Maybe(null)
```

yet when I execute it with `ramda-fantasy` i get:

![image](https://cloud.githubusercontent.com/assets/2054772/16694318/45090f4c-4542-11e6-871b-2de88769d8e6.png)

Should it be this way? is it a bug? Isn't `Maybe` checks nulls every time?

**Comment by davidchambers** [comment]
This is a common source of confusion. Though the Maybe data type allows us to avoid ever dealing with `null`, a Maybe should not inspect the value it may contain. In other words, the Maybe type should not treat any value specially. `Just(null)`, `Just(undefined)`, and `Just(NaN)` are perfectly valid values.

The function at fault here is `prop`. This function is fine for accessing a field of a "record": an object with known fields of know types. It appears that in this case the value is not a record. Instead, we're forced to treat the value as an amorphous object and make no assumptions about its properties.

What you want is a function such as [`S.get`][1]. It acknowledges the possibility of failure in two ways: the property may not exist; or the property may exist but its value may not be a member of the expected type.

```javascript
> S.get(Number, 'age', {name: 'Boris'})
Nothing()

> S.get(Number, 'age', {name: 'Boris', age: 42})
Just(42)
```

We can then use `chain` to apply an operation which may fail—`S.get(Number, 'age')`—to a Maybe:

```javascript
> R.chain(S.get(Number, 'age'), S.Just({name: 'Boris'}))
Nothing()

> R.chain(S.get(Number, 'age'), S.Just({name: 'Boris', age: 42}))
Just(42)
```

Wrapping the object is unnecessary. We can simply apply `S.get(Number, 'age')` to the object directly.

Putting it all together:

```javascript
//    agePlus10 :: Object -> Maybe Number
const agePlus10 = R.compose(R.map(R.add(10)), S.get(Number, 'age'));

agePlus10({name: 'Boris'});  // => Nothing()
agePlus10({name: 'Boris', age: 42});  // => Just(52)
```


[1]: http://sanctuary.js.org/#get

**Comment by buzzdecafe** [comment]
i agree with @davidchambers . Another way to look at it is that you did not anywhere define that getting `undefined` out of a function is an eror that should be wrapped in a `Nothing`. So `undefined` gets wrapped in a `Just` and passed to `add(10)`; again, nobody has said this is a problem -- JavaScript certainly doesn't care -- and so the final output is `Just(NaN)`

**Comment by Schniz** [comment]
So what is the purpose of `Maybe`? a convenient way of doing the `if (x != null) return Just...`? Is Sanctuary necessary? should I just implement `safeProp` myself?

```js
const safeProp = curry(compose(Maybe, prop));
```

Plus, should the book change? If the Maybe functor does not work this way

**Comment by buzzdecafe** [comment]
`Maybe` is there to capture the notion of "failure" without having to insert a null-check guard in every function. So I can compose function safely since my output types are well defined.

**Comment by davidchambers** [comment]
> ```javascript
> const safeProp = curry(compose(Maybe, prop));
> ```

The problem with this approach is that it fails to distinguish between `{}` and `{x: undefined}`. `safeProp('x', {x: undefined})` should evaluate to `Just(undefined)` rather than `Nothing`.

**Comment by CrossEye** [comment]
> The problem with this approach is that it fails to distinguish between `{}` and `{x: undefined}`. `safeProp('x', {x: undefined})` should evaluate to `Just(undefined)` rather than `Nothing`.

I think that's an API decision that one can make.  That the language has the ability to distinguish between these two feels more happenstance than fundamental.  The fact that one has to intentionally choose a more obscure testing method to distinguish them supports the notion that this might not be the best place to make a stand on a principle that "a value is a value".  I was reluctantly convinced that this is necessary for something like `Maybe` in order for it to remain lawful, but `safeProp` is not subject to those same constraints.
