### ISSUE TITLE
Some examples?

### ISSUE THREAD

**Issue by idcmardelplata** [ramda/ramda-fantasy#121]
Please, some examples of use of these cuties, thanks.

**Comment by scott-christopher** [comment]
You can find some examples in the docs for each type.

https://github.com/ramda/ramda-fantasy/tree/master/docs

Some of them will have more examples than others though, so let us know if there is something that you'd like more detail on.

**Comment by idcmardelplata** [comment]
Hi thanks for answering , I would like to know how I can get the value of Either , do you have some method to unwrap the value ?. Since already thanks

**Comment by scott-christopher** [comment]
There's a small section in the docs that describes how you can extract the value from an `Either` instance.

https://github.com/ramda/ramda-fantasy/blob/master/docs/Either.md#interaction
> Aside from the transformation methods mentioned above, Either.either can also be used to extract the value from an Either type, which takes a function to handle the type of value within the Left and another function to handle the type contained in the Right. Only one of these functions will be called depending on the constructor containing the value.

To illustrate with an example:
```js
lengthLeftDoubleRight = Either.either(R.length, R.multiply(2))

lengthLeftDoubleRight(Either.Left('moo')) //=> 3
lengthLeftDoubleRight(Either.Right(5))    //=> 10
```

**Comment by idcmardelplata** [comment]
Fantastic, thank you @scott-christopher !
