### ISSUE TITLE
Implement FantasyLand ChainRec

### ISSUE THREAD

**Issue by safareli** [ramda/ramda-fantasy#124]
As of [fantasyland/fantasy-land#152](https://github.com/fantasyland/fantasy-land/pull/152) implement [ChainRec](https://github.com/fantasyland/fantasy-land#chainrec) specification.

[MonadRec instance for either](https://github.com/purescript/purescript-tailrec/blob/master/src/Control/Monad/Rec/Class.purs#L89-L95) in purescript might be usefull

Here is [implementation](https://github.com/safareli/free/blob/e5fbbde2c50a1ec61968ec7c529aa3bb8ea51841/src/tailRec.js#L25-L98) of ChainRec for `folktale/data.task` with [tests](https://github.com/safareli/free/blob/e5fbbde2c50a1ec61968ec7c529aa3bb8ea51841/test/tailRecM.js) myght be usefull for `Future` (it's not quite correct as it is not handling cleanup stuff of the data.task but without that it works well)

I would create PR when have time.

**Comment by buzzdecafe** [comment]
> I would create PR when have time.

Excellent! Looking forward to it
