### ISSUE TITLE
Basic Future example

### ISSUE THREAD

**Issue by ShMcK** [ramda/ramda-fantasy#130]
I've been unable to get the most basic example of a working Future to work. I would suggest updating the documentation with a simple working version of a Future that returns a value.

```js
Future.of((reject, resolve) => {
  setTimeout(() => resolve('success'), 500)
}).fork(console.error, console.log)
// log: 'success'
// output: undefined
```

If `fork` is necessary to evaluate a Future, but `fork` can only return `undefined`, how is it possible to unwrap the computed value?

**Comment by Avaq** [comment]
Futures are asynchronous by nature, because they aim to add a degree of control flow to the otherwise hard to handle [async problem](https://github.com/plaid/async-problem).

Because of this, whenever a Future is evaluated, instead of getting the value *returned* in synchronous fashion, we get the value provided to a *callback*. You callback being `console.log`, in this case.

So if you wish to unwrap a Future, you have to continue processing inside your continuations:

```js
Future.of((reject, resolve) => {
  setTimeout(() => resolve('success'), 500)
})

//Continue processing, this only happens after 500ms, because we have no access to the value before.
.fork(console.error, (value) => {
  console.log('My value is: ' + JSON.stringify(value));
})
```

**Comment by ShMcK** [comment]
Thank you for taking the time to answer. I suppose what I'm trying to get at might best be explained by contrasting a Future with an ES6 Promise.

```js
const result = new Promise((resolve, reject) => {
  setTimeout(() => resolve('success'), 500)
})
// after 500 ms, logs: 'success'
```

However, `fork` does not return a value, even when the callback specifies a return, as in `x => x`. [REPL Example](https://goo.gl/pAZbNE).

```js
const result = Future.of((reject, resolve) => {
  setTimeout(() => resolve('success'), 500)
}).fork(console.error, x => x)
// undefined
```

Using `chain` after a `fork` also returns `undefined`, as `fork`'s type signature is `:: Future e a ~> (e -> ()) -> (a -> ()) -> ()`. [REPL Example](https://goo.gl/6Xg0xo).

```js
const result = Future.of((reject, resolve) => {
  setTimeout(() => resolve('success'), 500)
}).fork(console.error, x => x)
.chain(x => x)
// undefined
```

How can a Future be used to return a value, such that `result` is not `undefined`?

**Comment by Avaq** [comment]
Ahhh. I misunderstood your misunderstanding. I think I get it now. One of two things could be wrong here:

1. You are passing your computation to `Future.of` rather than `Future`. `Future.of(x)` is short for `Future((rej, res) => res(x))`, so you are constructing a Future which immediately resolves with a non-running computation.
2. You are attempting to `fork` prematurely. You can simply assign the Future to a variable, and `chain`, `map`, etc. as much as you please before finally calling `fork` to set the whole thing in motion.

**Comment by ShMcK** [comment]
Sorry for the difficulty, I'm still unable to assign the result of a basic Future to a variable.

In the following example: [See REPL](https://goo.gl/sUTKlv):

```js
let a = Future((rej, res) => res('success'))
  .chain(x => x)

a.fork(console.error, x => x)
// expected 'success', result: undefined
```

Perhaps an example might help.

**Comment by davidchambers** [comment]
You could use this as a starting point, @ShMcK:

```javascript
Future.of(42).fork(console.error, console.log);
```

Using `x => x` as the success handler means the result of the computation is ignored. ;)

**Comment by ShMcK** [comment]
@davidchambers, thank you. I can console.log the value of a Future, but I'm hoping to capture the result in a variable.

```js
const theValueShouldBe42 = Future.of(42).forkThatReturnsTheValueAfterAsynchronousProcess
```

I'd like to know what code I can write in `forkThatReturnsTheValueAfterAsynchronousProcess` that will return the value.

**Comment by eratio08** [comment]
@ShMcK 
`
const result = new Promise((resolve, reject) => {
  setTimeout(() => resolve('success'), 500)
})
`
will not result in the value - it will return a promise holding that value

**Comment by ShMcK** [comment]
So, my adjusted question again is:

Using 'ramda-fantasy' Future, how do you get a resulting value or resulting Future holding a value?

**Comment by eratio08** [comment]
You get a Future holding a value with Future.of(x) will result in a Future holding x. To acces the value you cant use .map(x => bla(x)). You start the processing of the future with .fork(errohandel(), finaleHandler()). 
Futures are like Promises: you can't get the value out of them direktly. Promises run directly Futures only after calling .fork(). 
You could try something like this (I'm a coding newbe)
```javascript
const x
Future.of('test').fork(console.error,y=>{y=x})
setTimeout(()=>console.log(x), 500)
```
The timeout will ensure that the future is resolved when you acces x

**Comment by ShMcK** [comment]
I think I get it now. 

My confusion was over how Futures get resolved, assuming they would be similar to Promises.

```js
it('basic Promise', async () => {
  let r = await new Promise((res, rej) => res('success'))
  expect(r).toBe('success')
}) // PASS

it('basic Future', async () => {
  let x
  let r = await F((rej, res) => res('success'))
      .fork(console.error, y => x = y)
  expect(x).toBe('success')
}) // PASS
```

Thank you for helping me sort that out.

**Comment by henriklundgren** [comment]
@ShMcK Maybe a cleaner solution,

```javascript
const promisify = (future) => {
  return new Promise((res, rej) => future.fork(rej, res));
}

async function foo() {
  try {
    const result = await promisify(Future.of('success'));
  } catch (error) {
  }
}

**Comment by TheLudd** [comment]
Just discovered this now and I didn't see it addressed in any of the answers, sorry if I missed it but @ShMcK your first example is incorrect
```
Future.of((reject, resolve) => {
  setTimeout(() => resolve('success'), 500)
}).fork(console.error, console.log)
```
You are calling `Future.of` the way you would call the constructor. Like others have pointed out, `of` takes a simple value. Change to:

```
Future((reject, resolve) => {
  setTimeout(() => resolve('success'), 500)
}).fork(console.error, console.log)
```
and it will work

**Comment by Izhaki** [comment]
I guess what @ShMcK was asking is: why does `fork` return `undefined` (instead of the value returned by the reject/resolve callbacks)?

The following code doesn't work:

```
export default
( sqlite ) => ( message ) => 
    messageToQuery( message )
    .either( Future.reject, executeQuery( sqlite ) )
    .fork( Promise.reject, Promise.resolve )
```

Because `fork` returns `undefined`. So the solution is:

```
export default
( sqlite ) => ( message ) => new Promise( (resolve, reject) => {
    messageToQuery( message )
    .either( Future.reject, executeQuery( sqlite ) )
    .fork( reject, resolve )
})
```

The answer is that `Future` may be async, so there's no way for `fork` returning a the chained value straight away.
