### ISSUE TITLE
Maybe.of should not create "Just" when we pass null

### ISSUE THREAD

**Issue by rajaraodv** [ramda/ramda-fantasy#134]
Maybe.of should not create "Just" when we pass null.

Maybe.of(null) should return Nothing()

**Comment by scott-christopher** [comment]
`Maybe.of` isn't really allowed to inspect the given value in order to satisfy various laws.

If you want that behaviour however, you can use `Maybe` as a constructor function to treat `null` and `undefined` as `Nothing`, otherwise wrapping the provided value in a `Just`.

```js
> RF.Maybe(null)
Nothing {}
> RF.Maybe(void 0)
Nothing {}
> RF.Maybe(1)
Just { value: 1 }
```

**Comment by rajaraodv** [comment]
I see. Thanks!
