### ISSUE TITLE
BUG: Maybe monad evaluated to 'Just { value: undefined }'

### ISSUE THREAD

**Issue by evandenrijd** [ramda/ramda-fantasy#135]
E.g. give me the string after the question-mark. So if we do NOT have a
    question-mark, we expect the Maybe monad to handle the undefined gracefully.
    But following test fails:

```
    expect(R.compose(
      R.map(R.nth(1)),
      R.map(R.split('?')))(Maybe('')))
    .toEqual(Maybe.Nothing())

```

We get something like:

>       Error: Expected { value: undefined } to equal {}
>       + expected - actual
> 
>       -{
>       -  "value": [undefined]
>       -}
>       +{}
> 

    So the map-method of Maybe should not use this.of(x) but Maybe(x) instead.

**Comment by davidchambers** [comment]
The proposed change would violate the [identity law][1]:

> `u.map(a => a)` is equivalent to `u` (identity)

```javascript
> Maybe.Just(undefined).map(x => x).equals(Maybe.Just(undefined))
false
```

The root of your problem is `R.map(R.nth(1))`. What you need is something like `R.chain(S.at(1))`, but this would require switching to Sanctuary. You could define your own `at :: Integer -> Array a -> Maybe a` function, though. :)


[1]: https://github.com/fantasyland/fantasy-land#functor

**Comment by evandenrijd** [comment]
How do I have to see the value Maybe.Just(undefined)? Is this of practical use?

In other words, should the identity law not only be valid for all values but the undefined/null?

```
> Maybe(undefined).map(x => x).equals(Maybe(undefined))
true

```

**Comment by davidchambers** [comment]
If we make an exception the Maybe type will no longer satisfy the requirements of the Functor type class. It would still be somewhat useful, but would no longer be compatible with functions such as [`lift2`][1] which are defined for all applicative functors. Making an exception would force us to define a Maybe-specific version of each function which can operate on any functor.


[1]: https://github.com/sanctuary-js/sanctuary-type-classes#lift2

**Comment by CrossEye** [comment]
The specification we've been following for those laws is the [FantasyLand][fa] one.  Here we're talking specifically the [Functor][fu] specification.


  [fa]: https://github.com/fantasyland/fantasy-land
  [fu]: https://github.com/fantasyland/fantasy-land#functor

**Comment by evandenrijd** [comment]
If I do the change in the code, all tests run as expected.
And as far as I can see all laws/tests of the FantasyLand are exerted/executed?

**Comment by TheLudd** [comment]
There is also this law https://github.com/fantasyland/fantasy-land#of-method
Check the very last line of that section

> No parts of a should be checked

**Comment by TheLudd** [comment]
This has also been discussed before. Both in this repo and here https://github.com/fantasyland/fantasy-land/issues/85

**Comment by evandenrijd** [comment]
Ok, I see you already had a similar discussion more then a year ago.

    So there seems to be a problem if you want a Functor (map) and Applicative
    (of and ap) all working together with there respective laws to form the
    Maybe Monad.

    I would be nice to see a test that, if (Functor, map, 1, iii), (Apply, ap,
    3, i) and (Applicative, of, 1, i) are broken the test fails, or if they are
    all broken similarly it will work (speculative guessing)?
