### ISSUE TITLE
Please implement Left.orElse on Either Monad to allow logging errors

### ISSUE THREAD

**Issue by rajaraodv** [ramda/ramda-fantasy#136]
//From Folktale https://github.com/folktale/data.either/blob/master/lib/either.js#L329
```
Left.prototype.orElse = function(f) {
  return f(this.value)
}
```
This helps us in providing error handling or logging functions to Either.
Usecase:
```
function divide(a, b) {
  return b === 0?  Left(new Error('Division by 0.')):  Right(a / b)
}
```

//call
`divide(1,0) //This throws error. So instead we can do:
`
With Left.orElse, we can do:
```
function Log(e) {
  console.log(2);
}
divide(1,0).orElse(log)
```

**Comment by buzzdecafe** [comment]
interested in doing a PR?

**Comment by rajaraodv** [comment]
I think I'll close this. I think we actually need catamorphism implemented instead of this. 
PS:
https://github.com/folktale/data.either/blob/master/lib/either.js#L368-L376

I think .cata is similar to Either.either but it can be chained using dot like below:

```
divide(1,0).cata({
  Left: err => console.error('fail :/', err),
  Right: str => console.log('boom', str)
})
```
