### ISSUE TITLE
Can Just(null) sort of behave like Nothing()?

### ISSUE THREAD

**Issue by bijoythomas** [ramda/ramda-fantasy#137]
Why is it that the map on Just cannot check for null/undefined before mapping over its contained value? Like:

`
Just.prototype.map = function(f) {
  return this.value? this.of(f(this.value)) : this
};
`

I can see how returning Nothing() form the beginning of a composed chain can prevent further mapping on the chain, but what if a mapping in the middle of a composed chain returns a Just(null).

`
Just(null).map(head) 
`

will throw the error Cannot read property '0' of null

**Comment by TheLudd** [comment]
=)
https://github.com/ramda/ramda-fantasy/issues/135
https://github.com/ramda/ramda-fantasy/issues/134
https://github.com/ramda/ramda-fantasy/issues/114
https://github.com/ramda/ramda-fantasy/issues/72
https://github.com/fantasyland/fantasy-land/issues/85

**Comment by TheLudd** [comment]
Use the `Maybe` constructor to get the behavior you want
`Maybe(null).map(head)`
