### ISSUE TITLE
Release to npm?

### ISSUE THREAD

**Issue by TheLudd** [ramda/ramda-fantasy#15]
Could that be done?

I think the version should be changed to something low, like `0.1.0` but I would really like it to be on npm just so that it will be easy to install to other projects for trying out. We could also update the readme to disclaim that this is pre alpha or what we would like to call it and that the API is running a high risk of being changed in this phase.

**Comment by buzzdecafe** [comment]
let me do PR for overloaded constructors and then let's do it

**Comment by TheLudd** [comment]
Sure thing

**Comment by buzzdecafe** [comment]
#16

**Comment by TheLudd** [comment]
Did the other stuff I mentioned in #17

**Comment by rockymadden** [comment]
:+1:

**Comment by buzzdecafe** [comment]
ok, will try to remember to publish tonight

**Comment by buzzdecafe** [comment]
https://www.npmjs.com/package/ramda-fantasy

**Comment by TheLudd** [comment]
:cake:

**Comment by CrossEye** [comment]
:fireworks:
