### ISSUE TITLE
Either equals implementation issue

### ISSUE THREAD

**Issue by henryqdineen** [ramda/ramda-fantasy#150]
`Either.Left(1).equals(Either.Right(1))` returns `true` but I think it should return `false`

**Comment by Avaq** [comment]
The problem is [here](https://github.com/ramda/ramda-fantasy/blob/master/src/Either.js#L31), and would probably be solved by something like this:

```diff
- Either.equals = Either.prototype.equals = util.getEquals(Either);
+ Left.equals = Left.prototype.equals = util.getEquals(Left);
+ Right.equals = Right.prototype.equals = util.getEquals(Right);
```
