### ISSUE TITLE
Does 'Maybe.map' not perform a null test 

### ISSUE THREAD

**Issue by egor-a-trubnikov-panov** [ramda/ramda-fantasy#163]
```js
import { Maybe} from 'ramda-fantasy'

Maybe(any)
    .map(value => null) // Just {value: null}
    .getOrElse('Error') // null

Maybe.of(null) // Just {value: null}
```

**Comment by davidchambers** [comment]
This is intentional. See #137 for links to prior discussions.

**Comment by Avaq** [comment]
* https://github.com/ramda/ramda-fantasy/issues/137
* https://github.com/ramda/ramda-fantasy/issues/135
* https://github.com/ramda/ramda-fantasy/issues/134
* https://github.com/ramda/ramda-fantasy/issues/114
* https://github.com/ramda/ramda-fantasy/issues/72
* https://github.com/ramda/ramda-fantasy/issues/61
* https://github.com/sanctuary-js/sanctuary/issues/328
* https://github.com/fantasyland/fantasy-land/issues/261
* https://github.com/fantasyland/fantasy-land/issues/85
