### ISSUE TITLE
Add Future#fromPromise

### ISSUE THREAD

**Issue by alexandrethsilva** [ramda/ramda-fantasy#164]
Hi guys,
I was discussing with @gunar about how Ramda-Fantasy's`Future` compares to Folktale's and he mentioned that it was unfortunate that there's no `Future.fromPromise`.

It got me thinking if that's because the lib wants to stick to a strictly FP-like interface–i.e. implement only the functionality expected from the respective Types and leave the rest to whomever is consuming them–or if there's space for a PR implementing this?

Of course we can always just make a wrapper ourselves, but I thought it could be a handy method for many?

I could give it a try in case there is, but thought of first opening an issue to get your input.

**Comment by CrossEye** [comment]
Please see #157.  This project is closing down, with a number of great alternatives available.

**Comment by gunar** [comment]
@alexandrethsilva Yup, that's what I figured

**Comment by alexandrethsilva** [comment]
@CrossEye thanks for pointing that out!

**Comment by buzzdecafe** [comment]
Also check out [Fluture](https://github.com/fluture-js/Fluture)
