### ISSUE TITLE
Is it wrong to call "runIO()" twice?

### ISSUE THREAD

**Issue by Djordjenp** [ramda/ramda-fantasy#176]
Hello, 
I am trying to take element from the DOM and set it's text content, but I end up calling "runIO()" twice, because my IO action returns another IO:
```
import {IO} from "ramda-fantasy";

const logger = data => IO(() => console.log(data));
const getElement = id => IO(() => document.querySelector(id))
const setElementText = element => text => IO( () =>element.textContent = text)

const someText = IO(() => 'New Title')

getElement('h1').map(setElementText).ap(someText).runIO().runIO();
```
I am aware that I can swap argument positions in "setElementText" function, but I am interested is there a solution for this kind of stuff.  Maybe I can use ramda's chain function to unwrap this inner IO somehow?

**Comment by CrossEye** [comment]
Note that this project has long been deprecated.  None of its developers are currently active.  The Ramda team recommends switching to another implementation.

https://github.com/ramda/ramda-fantasy/blob/master/README.md#project-status

**Comment by davidchambers** [comment]
Shall we archive this project, @CrossEye?

**Comment by CrossEye** [comment]
@davidchambers: perhaps.  I still use it occasionally, but always from the NPM repo.

I haven't dealt with archiving a project before, so I'm not sure what it would entail.  For the moment, I'll pin an issue that explains what's also in the README.
