### ISSUE TITLE
upgrade types to monoid where sensible

### ISSUE THREAD

**Issue by buzzdecafe** [ramda/ramda-fantasy#27]
then setoid can come off the table on README

**Comment by TheLudd** [comment]
Acutally, setiod stands on it's own. Monoids must also implement semigroup.

That said, I would surely not object to this addition. My main problem is that I don't understand what monoids are about. The specification of the `empty` method leaves a lot to the imagination.

**Comment by buzzdecafe** [comment]
Just discussing this with @CrossEye. _Generic_ Monoid may be a little weird in dynamically-typed JS. 

Consider a `Maybe` monoid: It depends on how you interpret `Nothing`: does it mean "empty list"? In that case `Just(1).concat(Nothing) => Just(1)` . Or does `Nothing` mean "failed computation"? In that case, `Just(1).concat(Nothing) => Nothing`. The question is, are *both* of these lawful? If so, how do we choose between them?

**Comment by CrossEye** [comment]
I need to go back and raise a pull-request on FantasyLand regarding how `of` and `empty` are defined in the spec.  There's an [old issue](https://github.com/fantasyland/fantasy-land/issues/88) that discusses the problem.  I'm just not sure enough of myself there to know exactly _what_ should be in that PR.

The other issue is that I don't think you can have a `Maybe` monoid, only  `Maybe(String)` or `Maybe(List)` or `Maybe(Add)`, etc. ones.  And I don't think ramda-fantasy has tried to define such.

**Comment by buzzdecafe** [comment]
i think i am favoring the former definition, viz, `Just(1).concat(Nothing) => Just(1)` (and `Nothing.concat(Just(1)) => Just(1)`, but I have no *strong* basis for doing so. 

Incidentally, wikipedia desription of a monoid is pretty clear: http://en.wikipedia.org/wiki/Monoid
