### ISSUE TITLE
Utility functions of varying purity

### ISSUE THREAD

**Issue by TheLudd** [ramda/ramda-fantasy#28]
I did some experimentation today and hacked together `futurify` and `futurifyAll` functions inspired by bluebirds [promisify](https://github.com/petkaantonov/bluebird/blob/master/API.md#promisepromisifyfunction-nodefunction--dynamic-receiver---function) and [promisifyAll](https://github.com/petkaantonov/bluebird/blob/master/API.md#promisepromisifyallobject-target--object-options---object).

I was wondering if this is of interest for ramda fantasy. Would they be something that we would want to put in this project, a separate utility-project or not in ramda at all?

**Comment by buzzdecafe** [comment]
i like the idea of a lib of shims, to connect ramda-fantasy with whatever else you wanna connect it to. this could be a candidate for that, and i'd also put `commute` and `commuteMap` in there

**Comment by TheLudd** [comment]
I'd say `commute` and `commuteMap` are much more related to the types in this library and for me they would belong much more here. I feel that the usage of those functions are closely linked to the usage of type classes. And the `futurifyAll` is more of a necessary dirty thing.

**Comment by buzzdecafe** [comment]
status on this @TheLudd ? PR forthcoming?

**Comment by TheLudd** [comment]
This was more intended as a discussion of whether to include functions related to the fanstasy land types  at all in this project, as opposed to just including the types themselves. Since this has already begun with `lift` we can close this. Any other function can be included in a PR/discussion of its own.

**Comment by joneshf** [comment]
For those of us not familiar with bluebird, what do `futurify`/`futurifyAll` do?

**Comment by TheLudd** [comment]
It would transform a function that expects a node callback as its last argument into a function that returns a `Future` instead. Futurify all would do so for all functions in a given object.

Inspired by https://github.com/petkaantonov/bluebird/blob/master/API.md#promisification
