### ISSUE TITLE
define Future equality

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda-fantasy#3]
Currently `Future.prototype.equals` always returns true.

**Comment by TheLudd** [comment]
I sneaked at [data.task](https://github.com/folktale/data.task) and they do not have an equal method on futures but they have defined a test function that determines equality. It only works for synchronous Futures but is useful in tests. Perhaps that is the way to go?

**Comment by buzzdecafe** [comment]
> It only works for synchronous Futures but is useful in tests. Perhaps that is the way to go?

better than what i got

**Comment by buzzdecafe** [comment]
cloed by https://github.com/ramda/ramda-fantasy/pull/13
