### ISSUE TITLE
Proposal: Pair & Tuple functor

### ISSUE THREAD

**Issue by branneman** [ramda/ramda-fantasy#34]
### Background
This started as [issue 1048](https://github.com/ramda/ramda/issues/1048) at the [ramda](https://github.com/ramda/ramda) repository. I'm working with 2-dimensional arrays where the nested arrays are all length-2, I've imagined them as being tuple pairs. My first needs were the `fst` and `snd` functions in Ramda to handle those pairs. Later we talked about creating a `Pair` or `Tuple` functor, which might be more useful in general.

I've fooled around a bit in [this Gist](https://gist.github.com/branneman/e26f2339b705cff557e6), however I'm not satisfied with the results so far. (Is my use of `.of()` correct? Do I understand the [Applicative specification](https://github.com/fantasyland/fantasy-land#applicative) at all?)

But lets first answer: what should the API be?

### API Examples

Given an array:
```js
var pair1 = Pair(['one', 2]);
fst(pair1); //=> 'one'
snd(pair1); //=> 2
```

Given 2 arguments:
```js
var pair2 = Pair('one', 2);
fst(pair2); //=> 'one'
snd(pair2); //=> 2
```

Creating instances with `Pair.of()`:
```js
var text = ['one', 'two', 'three'], numbers = [1, 2, 3];
R.map(Pair.of, R.zip(text, numbers)); //=> [Pair, Pair, Pair]
```

### Implementation

@DrBoolean suggested an array-friendly solution, which plays nice with `R.nth()` and `R.head()`:
```js
var _Tuple = function(x, y) {
  this[0] = x;
  this[1] = y;
  this.length = 2;
}
```

As a last remark, I personally don't think I'm qualified, since my functional programming on the level of algebraic structures is afaik not good enough. I've started learning Haskell but I'm mainly still figuring things out. I would love to help out, but don't let me slow you down.

**Comment by davidchambers** [comment]
#33 is a related thread.

**Comment by branneman** [comment]
Oh, I see the work is already almost done. Awesome!

**Comment by buzzdecafe** [comment]
> As a last remark, I personally don't think I'm qualified, since my functional programming on the level of algebraic structures is afaik not good enough. 

hey, same for me! best way to learn it is to do it IMO. so don't let that discourage you.
