### ISSUE TITLE
use eqDeep in equals methods

### ISSUE THREAD

**Issue by buzzdecafe** [ramda/ramda-fantasy#35]

**Comment by buzzdecafe** [comment]
`R.eqDeep(x, y)` rather than `x === y`

**Comment by TheLudd** [comment]
Sounds good. I have been considering this myself as well.

**Comment by buzzdecafe** [comment]
can is be defined generically I wonder: 

```js
function mkEqFn(type) {
  return function equals(y) {
    y instanceof type && eqDeep(this, y);
  };
}
```

and then:

```js
X.prototype.equals = util.mkEqFn(X);
```

?

**Comment by TheLudd** [comment]
Well...
If possible it might be easier to create the common function first and have it work the same way it does now. If that refactoring works well then it can just be changed to eqDeep afterwards.
