### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by yemi** [ramda/ramda-fantasy#39]
Would be nice to download this using bower

**Comment by buzzdecafe** [comment]
good idea. will try to put that together this weekend

**Comment by yemi** [comment]
Awesome :+1:

**Comment by buzzdecafe** [comment]
unless you wanna do a PR sooner ....

**Comment by yemi** [comment]
Ofc, Ill give it a shot as soon as i get some time over

**Comment by TheLudd** [comment]
Do we have a known strategy for packing this project into a browser-friendly format?

**Comment by buzzdecafe** [comment]
not yet. but we absolutely should decide on that.
