### ISSUE TITLE
needs UMD wrapper

### ISSUE THREAD

**Issue by ChetHarrison** [ramda/ramda-fantasy#43]
I am transpiling my es6 to AMD modules with Babel. I may take a shot at putting this lib in the UMD wrapper so it will work with both flavors of modules.

**Comment by ChetHarrison** [comment]
hmm. looks like we would need to put in a build step

**Comment by buzzdecafe** [comment]
yes, build step would be necessary. we could simply browserify, or do something like the build script in ramda/ramda

**Comment by ChetHarrison** [comment]
yes the ramda script would work

**Comment by ChetHarrison** [comment]
I was so damn excited to play with it I just up and copied the things I wanted for the time being.

**Comment by remojansen** [comment]
:+1: It would be great if after `npm install ramda-fantasy` it could be imported directly in a web browser as a global.
