### ISSUE TITLE
Docs and site

### ISSUE THREAD

**Issue by TheLudd** [ramda/ramda-fantasy#60]
I think that this library is quite useful in its current state but the impression is not that good when looking at the code. One reason is the lack of documentation and structure. I have never used jsdoc myself (other than to write it in working environments). Is there anyone with knowledge that knows what it will take to generate documentation? I think that a site with published documentation would greatly improve the status of this project.

**Comment by CrossEye** [comment]
Clean-up would definitely be helpful, as would documentation.

I've never really liked the tag format of JSDoc, and would definitely consider using [Transcribe][tr] or some other tool, but perhaps it would be better to be consistent across all the Ramda projects?

The big trouble is that I have little appetite for doing this documentation.  If there are people interested in doing it, I'd be willing to help get the infrastructure in place.


  [tr]: https://github.com/plaid/transcribe

**Comment by TheLudd** [comment]
Documenting it will be a big task but I am sure willing to contribute. I think I will be better at documenting than setting up infrastructure. And I have no specific preference in what tool to use.

**Comment by davidchambers** [comment]
I'm clearly biased, but I've never enjoyed writing documentation for a project as much as I enjoy writing documentation for Sanctuary. There are several reasons for this:

  - there is exactly *one* source file;
  - docstrings can contain arbitrary (GitHub Flavored) Markdown;
  - all the examples are tested by `make test`; and
  - Transcribe is a very good fit for functional programming libraries (unlike JSDoc).

I strongly recommend doing something similar here. Don't copy Ramda's mistake! ;)

**Comment by buzzdecafe** [comment]
> * there is exactly one source file;

not an option here. it may be nice to have separate docfiles from the source, though.

> * all the examples are tested by make test; and

ok

> * Transcribe is a very good fit for functional programming libraries (unlike JSDoc).

i dunno, who authored that? Is he even american? :stuck_out_tongue_winking_eye:

**Comment by TheLudd** [comment]
> i dunno, who authored that? Is he even american?

Think he is from the more good looking part of the world... :wink:

**Comment by CrossEye** [comment]
@buzzdecafe:

>> * there is exactly one source file;

> not an option here. it may be nice to have separate docfiles from the source, though.

I think the point is that there can be a separate _single_ docfile to document the entire system.  This sounds good to me.  It would be better if it could be broken up arbitrarily into whatever groups seem appropriate and combined by the doc parser.  I haven't looked enough to know if this is possible.

**Comment by scottcorgan** [comment]
Any progress on this? The tests are mostly helpful, but seeing real usage examples would be great!

**Comment by TheLudd** [comment]
If there is no better concrete suggestion I'd go forward with jsdoc.

**Comment by scottcorgan** [comment]
Even just links to working JSBins would be awesome!

**Comment by walkermalling** [comment]
If your goal is to make ramda-fantasy more accessible (i.e. to javascript developers who haven't experimented with Haskel, and for whom ramda-fantasy might be their first introduction to monads and fantasyland), consider using the wiki to present a few uses for each export (there are only 9, after all).  Presenting type signatures, or re-expressing which specs each monad implements is really not going to be enough of an introduction to the library.

**Comment by CrossEye** [comment]
I agree that some further documentation will be necessary.  I've stalled in documenting the [main library][rm] (although I do have some work not checked in) and documenting secondary projects is still more work.  I'd love to see it happen, but I think it's going to take someone stepping forward.


  [rm]: https://github.com/ramda/ramda/issues/1282

**Comment by nschurmann** [comment]
Please!, the documentation would be great for non-haskell developers. We are implementing this library with a lot of effort only reading and trying to understand what everything does.

**Comment by stoeffel** [comment]
I started doing some work on this, because I think this library is great and deserves some documentation. I will proceed with it if you guys like my approach.
It's a simple [bash-script](https://github.com/stoeffel/ramda-fantasy/blob/docs/scripts/build-docs) which runs [transcribe](https://github.com/plaid/transcribe) for all files in `src` and creates a [API.md](https://github.com/stoeffel/ramda-fantasy/blob/docs/API.md#identity).

**Comment by davidchambers** [comment]
@stoeffel, have you seen #84?

**Comment by stoeffel** [comment]
Oh no, didn't see that :blush:

**Comment by scott-christopher** [comment]
An initial pass at documentation for the various types is now available:
https://github.com/ramda/ramda-fantasy/tree/master/docs

I welcome issues / PRs for improvements.

**Comment by stoeffel** [comment]
@scott-christopher looks great. Will check it out.
