### ISSUE TITLE
Map of Just should produce a Nothing when function produces a null or undefined

### ISSUE THREAD

**Issue by jordalgo** [ramda/ramda-fantasy#61]
Forgive me if there is an obvious answer for this (I'm new to Maybes and Monads). If you call 'map' on a Just and that function produces a 'null' or 'undefined' shouldn't a new Nothing be created as opposed to a Just that contains a null value?

Example:

```javascript
maybe([12]).map(function() { return null; });
/=> Just { value: null }
```

https://github.com/ramda/ramda-fantasy/blob/master/src/Maybe.js#L47

**Comment by TheLudd** [comment]
I think the way to do it is to not use functions that return `undefined` but rather a `Maybe` and then you can use `chain` instead of `map`.

**Comment by davidchambers** [comment]
I agree with @TheLudd.

**Comment by jordalgo** [comment]
@TheLudd @davidchambers Thanks for the quick reply! I guess I feel like a Just should never be filled with a null or undefined value and that calling map on a Maybe functor with a null value (this is before you know it's a Just or Nothing in a function pipeline) should evaluate to a Nothing. Similar to @DrBoolean 's implementation of a [Maybe](https://github.com/DrBoolean/mostly-adequate-guide/blob/master/ch8.md).

**Comment by davidchambers** [comment]
I don't think a library should decide which values should and should not be used. `null` and `undefined` are JavaScript values. In some cases they are valid *success* values. For example:

```javascript
> S.parseJson('null')
Just(null)
> S.head([undefined, 2, 3])
Just(undefined)
```

Having either of these expressions evaluate to `Nothing()` would breach a contract: [`S.parseJson`][1] should return `Nothing()` only if parsing fails; [`S.head`][2] should return `Nothing()` only if the list is empty.


[1]: https://github.com/plaid/sanctuary#parseJson
[2]: https://github.com/plaid/sanctuary#head

**Comment by buzzdecafe** [comment]
> a library [should not] decide which values should and should not be used ... In some cases they are valid _success_ values.

That's exactly the problem. ramda-fantasy *used to* behave as you suggest, viz:

```js
function Maybe(x) {
  return x == null ? Nothing() : Just(x);
}
```

but this is too prescriptive.

**Comment by TheLudd** [comment]
@buzzdecafe That is how it behaves today. Did you describe the wrong function? (constructor instead of map).

**Comment by TheLudd** [comment]
@jordalgo 

>  I guess I feel like a Just should never be filled with a null or undefined value

The way I tend to think these days is that a function should never return `null` or `undefined`. I believe that is a better approach. Perhaps more cumbersome if you consider reality but not unfeasible. 

Never returning `null` or `undefined` feels more like "stop the problem at the source" to me.

**Comment by jordalgo** [comment]
@TheLudd (again I'm a noob on this) but I thought that was kind of the point of Maybes in JS, as per the constructor which filters on 'null' values passed into it. A Maybe should be resilient enough to handle null values in future map calls when the value can become null.

**Comment by buzzdecafe** [comment]
@TheLudd hmm, must've changed back!

**Comment by joneshf** [comment]
@jordalgo the problem is, when you start inspecting vakues and dispatching on them, the data structure stops obeying laws. That `Maybe` by @DrBoolean is not a `Functor`, it breaks the composition law.

@buzzdecafe there's nothing wrong with having a factory, so long as it is recognized that the factory can't be used in functions that are supposed to be lawful (which the current implementation adheres to).

**Comment by DrBoolean** [comment]
I'm 100% in favor of Just/Nothing. @joneshf how does it break composition?

**Comment by DrBoolean** [comment]
Oh oh, I gotcha. In the case of null/undefined. Truth

**Comment by jordalgo** [comment]
I think I understand; because the initial Maybe evaluates to either a Just or a Nothing, if you re-evaluate a possible Just to a Nothing the composition law does break e.g.

``` javascript
var R = require('ramda');
var compLaw1 = R.compose(R.map(function(d){ return d + ' World'; }), R.map(R.always(null)));
var compLaw2 = R.map(R.compose(function(d){ return d + ' World'; }, R.always(null)));

compLaw1(Maybe("Hello")); /=> _Nothing {}
compLaw2(Maybe("Hello")); /=> _Just {value: "null World"}
```

So just for my understanding (and thanks everyone for the quick lesson!), the @DrBoolean Maybe isn't a functor because it applies additional evaluation to the contained value instead of just applying the passed function?

**Comment by joneshf** [comment]
@DrBoolean yeah it threw me as well: https://github.com/fantasyland/fantasy-land/issues/85#issuecomment-73419882

@jordalgo yep.

**Comment by jordalgo** [comment]
Thanks @joneshf and all. Wish I had read that older discussion first :).
