### ISSUE TITLE
Release 0.4.0

### ISSUE THREAD

**Issue by TheLudd** [ramda/ramda-fantasy#68]
Are we good with releasing current master as 0.4.0?

**Comment by buzzdecafe** [comment]
:+1:

**Comment by TheLudd** [comment]
Done

**Comment by TheLudd** [comment]
Just realized that I ran `npm version minor` before release and not the `xyz` thing. Did I screw up?

**Comment by davidchambers** [comment]
`"version"` in __bower.json__ was not updated, but according to davidchambers/xyz#19 we should remove this field as it's not used.
