### ISSUE TITLE
Maybe

### ISSUE THREAD

**Issue by ChetHarrison** [ramda/ramda-fantasy#72]
wouldn't you want to implement the `Maybe` constructor and the  `Maybe.of` method like this:
```
function Maybe( x ) {
	return ( x === null || x === undefined ) ? _nothing : Maybe.Just( x );
}

Maybe.of = function( x ) {
    return new Maybe( x );
}
```
Currently if I do something like this
```
Maybe.of( undefined );
```
I get back a `_Just {value: undefined}`

**Comment by TheLudd** [comment]
That would break the specification. I myself asked the same thing a while back =)
https://github.com/fantasyland/fantasy-land/issues/85

**Comment by ChetHarrison** [comment]
hmm ok. I'll look at it again. How would you use it to guard against `undefined` value?

**Comment by TheLudd** [comment]
`var m = new Maybe(someValue)`

`m` will be an instance of `Nothing` if `someValue` is `null` or `undefined`

**Comment by TheLudd** [comment]
You can also skip the `new` if you'd like

**Comment by davidchambers** [comment]
> How would you use it to guard against `undefined` value?

With Sanctuary one would simply filter after the fact:

```javascript
> R.reject(R.isNil, S.Just(null))
Nothing()
```

ramda-fantasy provides the `== null` behaviour mentioned by @TheLudd (which is questionable, in my view).

**Comment by buzzdecafe** [comment]
`var m = new Maybe(someValue)`

no need to use `new` here since `Maybe` is really a `Just | Nothing` factory, not a constructor

**Comment by ChetHarrison** [comment]
ok. Thanks. In the future is it better to memorialize these discussions here or Gitter?

**Comment by davidchambers** [comment]
GitHub issues are easier to reference, but either is fine.

**Comment by ChetHarrison** [comment]
:+1:
