### ISSUE TITLE
Reader ask

### ISSUE THREAD

**Issue by davidchase** [ramda/ramda-fantasy#74]
Should `Reader.ask` equal `Reader(R.identity)` ?  so the following would work
```js
const append = str => Reader.ask.map((strToo) => str.concat(' ', strToo));
const greet = R.compose(R.chain(append), Reader.of);
greet('hello').run('world'); //=> hello world
```

rather current with `Reader.ask = Reader(R.always)`

```js
const append = str => Reader.ask.map((strToo) => str.concat(' ', strToo()));
const greet = R.compose(R.chain(append), Reader.of);
greet('hello').run('world');  //=> hello world
```

you need to call `strToo()`...

**Comment by scott-christopher** [comment]
You're correct. It should be using `identity`. I'll raise a PR shortly.

Thanks for raising it.

**Comment by scott-christopher** [comment]
I've raised https://github.com/ramda/ramda-fantasy/pull/76 to fix this.

Thanks again.

**Comment by davidchase** [comment]
cool :+1: thanks for looking into it

**Comment by TheLudd** [comment]
We could release this as a patch version

**Comment by scott-christopher** [comment]
I've just pushed out 0.4.1
