### ISSUE TITLE
Maybe and Either have different "commute" semantics

### ISSUE THREAD

**Issue by davidchambers** [ramda/ramda-fantasy#75]
Commuting a list of Maybes results in a Nothing if any of the elements if a Nothing:

```javascript
> R.commute(Maybe.of, [Maybe.Just(1), Maybe.Just(2)])
Maybe.Just([1, 2])
> R.commute(Maybe.of, [Maybe.Just(1), Maybe.Just(2), Maybe.Nothing()])
Maybe.Nothing()
```

Commuting a list of Eithers results in a Right whose value is a list containing each Right's value:

```javascript
> R.commute(Either.of, [Either.Right(1), Either.Right(2)])
Either.Right([1, 2])
> R.commute(Either.of, [Either.Right(1), Either.Right(2), Either.Left('XXX')])
Either.Right([1, 2])
```

**Comment by CrossEye** [comment]
So, are you suggesting that this is a bad thing?

Do you think that `commute` should change?  Or `ap`?  Or `Maybe`/`Either`?

**Comment by davidchambers** [comment]
> So, are you suggesting that this is a bad thing?

Yes. I view `Maybe a` as a convenient type for situations in which one would otherwise use `Either () a`. I expect the two types to handle success and failure in the same way.

> Do you think that `commute` should change? Or `ap`? Or `Maybe`/`Either`?

It seems to me that `Either#ap` is broken:

```javascript
> Either.Right(R.inc).ap(Either.Right(42))
Either.Right(43)

> Either.Right(R.inc).ap(Either.Left('XXX'))
Either.Left("XXX")

> Either.Left('XXX').ap(Either.Right(42))
Either.Right(42)

> Either.Left('XXX').ap(Either.Left('YYY'))
Either.Left("YYY")
```

I expect the third and four expressions to evaluate to `Either.Left('XXX')`. The third case is particularly strange: a failure value is transformed into a success value.

**Comment by joneshf** [comment]
> So, are you suggesting that this is a bad thing?

He's showing that `Either` is broken somewhere.

**Comment by joneshf** [comment]
All the more reason to get some better testing in place. A property based test could flesh out these bugs fairly trivially if done correctly.

**Comment by CrossEye** [comment]
> ```javascript
> > Either.Left('XXX').ap(Either.Right(42))
> Either.Right(42)
> 
> > Either.Left('XXX').ap(Either.Left('YYY'))
> Either.Left("YYY")
> ```

Fantasy-land seems to [leave these unspecified][fl].

> A value which has an Apply must provide an `ap` method. The `ap` method takes one argument:
> 
>     a.ap(b)
> 
> 1. `a` must be an Apply of a function,
> 
>    1. If `a` does not represent a function, the behaviour of `ap` is unspecified.

Obviously the value in .`Left('XXX')` is not a function.

Unspecified, of course, allows us to do as we see fit.  But it's not clear to me _what_ we should do.  If we think of these as `Left -> Error(String), Right -> Value`, then it's pretty simple to say that

```js
Left.prototype.ap = function(b) {
    return new Left(this.value);
}
```

But `Either` in fact can model an arbitrary disjunction.  How would you handle this?:

```js
Either.Left(R.inc).ap(Either.Right(42))
```

Ours seems to have the same behavior as [Folktale's implementation][ft].  It certainly seem unloveable in either place.  But I don't have a suggested replacement.  Do you?

  [fl]: https://github.com/fantasyland/fantasy-land#ap-method 
  [ft]: https://github.com/folktale/data.either/blob/master/lib/either.js#L178-L186

**Comment by davidchambers** [comment]
> Obviously the value in .`Left('XXX')` is not a function.

This is not necessarily the right way to look at it. In order for a value of type `Either a b` to be "an Apply of a function", `b` must be of type `x -> y`, but there are no constraints on `a`. `Left('XXX')` and `Right(R.inc)` both inhabit `Either String (Number -> Number)`.

> `Either` [can] in fact can model an arbitrary disjunction. How would you handle this?:
>
> ```javascript
> Either.Left(R.inc).ap(Either.Right(42))
> ```

I would defer to Haskell:

```haskell
> :t Left (+ 1) <*> Right 42
Left (+ 1) <*> Right 42 :: Num a => Either (a -> a) b
```

In other words, the expression should evaluate to `Either.Left(R.inc)`.

> I don't have a suggested replacement. Do you?

I would have `Left#ap` return `this`, as you suggest. [`S.Either#ap`][1] behaves this way, and following Haskell's lead on these matters is usually sound.


[1]: https://github.com/plaid/sanctuary#Either.prototype.ap

**Comment by joneshf** [comment]
It seems like `ap` isn't so much broken, as it just has different semantics. I say seems because I haven't taken the time to prove one way or the other.

However, whether `ap` is actually broken, `Either` is surely not an `Applicative`:

```coffeescript
coffee> Left('XXX').ap(Either.of(3))
_Right { value: 3 }
coffee> Either.of((f) => f(3)).ap(Left('XXX'))
_Left { value: 'XXX' }
```

It breaks at least the interchange law, maybe others.

**Comment by CrossEye** [comment]
> In other words, the expression should evaluate to `Either.Left(R.inc)`.
> 
> > I don't have a suggested replacement. Do you?
> 
> I would have `Left#ap` return `this`, as you suggest. [`S.Either#ap`][1] behaves this way, and following Haskell's lead on these matters is usually sound.

This certainly sounds reasonable to me.  But I'm entirely unsure if this is reasonable semantics or not, or even if it's lawful behavior.  I still have not spent much time with Ramda-Fantasy.  Some day...

I agree with @joneshf (in Gitter?) that we might be able to avoid some of this with some more thorough testing.


[1]: https://github.com/plaid/sanctuary#Either.prototype.ap

**Comment by TheLudd** [comment]
This definetly looks wrong.
https://github.com/ramda/ramda-fantasy/blob/master/src/Either.js#L71

For all I know this should be:
```
_Left.prototype.ap = function(_) { 
  return this; 
};
```

**Comment by CrossEye** [comment]
@TheLudd: I think so.  We've taken a lot of inspiration from Folktale, [perhaps too much][ft].

Anyone want to take a swing at demonstrating that `Either` changed this way would be lawful?

  [ft]: https://github.com/folktale/data.either/blob/master/lib/either.js#L178-L186

**Comment by davidchambers** [comment]
> Anyone want to take a swing at demonstrating that `Either` changed this way would be lawful?

Sanctuary's test suite asserts that [`S.Left`][1] and [`S.Right`][2] obey identity, homomorphism, and interchange.


[1]: https://github.com/plaid/sanctuary/blob/v0.7.1/test/index.js#L1134-L1148
[2]: https://github.com/plaid/sanctuary/blob/v0.7.1/test/index.js#L1341-L1355

**Comment by joneshf** [comment]
I was getting ready to rebut the current implementation being wrong on the basis of it being different, but I decided to prove its correctness instead. I don't reduce all the way, just enough to show that the two sides are either equal or not.

```js
// Left Left Left

Left(u).map(f => g => x => f(g(x))).ap(Left(v)).ap(Left(w))         // LHS
    = Left(u).ap(Left(v)).ap(Left(w))                               // Left#map
    = Left(v).ap(Left(w))                                           // Left#ap

Left(u).ap(Left(v).ap(Left(w)))                                     // RHS
    = Left(v).ap(Left(w))                                           // Left#ap

// Left Left Right

Left(u).map(f => g => x => f(g(x))).ap(Left(v)).ap(Right(w))        // LHS
    = Left(u).ap(Left(v)).ap(Right(w))                              // Left#map
    = Left(v).ap(Right(w))                                          // Left#ap

Left(u).ap(Left(v).ap(Right(w)))                                    // RHS
    = Left(v).ap(Right(w))                                          // Left#ap

// Left Right Left

Left(u).map(f => g => x => f(g(x))).ap(Right(v)).ap(Left(w))        // LHS
    = Left(u).ap(Right(v)).ap(Left(w))                              // Left#map
    = Right(v).ap(Left(w))                                          // Right#ap

Left(u).ap(Right(v).ap(Left(w)))                                    // RHS
    = Right(v).ap(Left(w))                                          // Left#ap

// Left Right Right

Left(u).map(f => g => x => f(g(x))).ap(Right(v)).ap(Right(w))       // LHS
    = Left(u).ap(Right(v)).ap(Right(w))                             // Left#map
    = Right(v).ap(Right(w))                                         // Right#ap

Left(u).ap(Right(v).ap(Right(w)))                                   // RHS
    = Right(v).ap(Right(w))                                         // Left#ap

// Right Left Left

Right(u).map(f => g => x => f(g(x))).ap(Left(v)).ap(Left(w))        // LHS
    = Right((f => g => x => f(g(x)))(u)).ap(Left(v)).ap(Left(w))    // Right#map
    = Left(v).map((f => g => x => f(g(x)))(u)).ap(Left(w))          // Right#ap
    = Left(v).ap(Left(w))                                           // Left#map
    = Left(w)                                                       // Left#ap

Right(u).ap(Left(v).ap(Left(w)))                                    // RHS
    = Left(v).ap(Left(w)).map(u)                                    // Right#map
    = Left(w).map(u)                                                // Left#ap
    = Left(w)                                                       // Left#map

// Right Left Right
// **This one fails**

Right(u).map(f => g => x => f(g(x))).ap(Left(v)).ap(Right(w))       // LHS
    = Right((f => g => x => f(g(x)))(u)).ap(Left(v)).ap(Right(w))   // Right#map
    = Left(v).map((f => g => x => f(g(x)))(u)).ap(Right(w))         // Right#ap
    = Left(v).ap(Right(w))                                          // Left#map
    = Right(w)                                                      // Left#ap

Right(u).ap(Left(v).ap(Right(w)))                                   // RHS
    = Left(v).ap(Right(w)).map(u)                                   // Right#map
    = Right(w).map(u)                                               // Left#ap
    = Right(u(w))                                                   // Right#map

// Right Right Left

Right(u).map(f => g => x => f(g(x))).ap(Right(v)).ap(Left(w))       // LHS
    = Right((f => g => x => f(g(x)))(u)).ap(Right(v)).ap(Left(w))   // Right#map
    = Right(v).map((f => g => x => f(g(x)))(u)).ap(Left(w))         // Right#ap
    = Right((f => g => x => f(g(x)))(u)(v)).ap(Left(w))             // Right#map
    = Left(w).map((f => g => x => f(g(x)))(u)(v))                   // Right#ap
    = Left(w)                                                       // Left#map

Right(u).ap(Right(v).ap(Left(w)))                                   // RHS
    = Right(v).ap(Left(w)).map(u)                                   // Right#map
    = Left(w).map(v).map(u)                                         // Right#ap
    = Left(w).map(u)                                                // Left#map
    = Left(w)                                                       // Left#map

// Right Right Right

Right(u).map(f => g => x => f(g(x))).ap(Right(v)).ap(Right(w))      // LHS
    = Right((f => g => x => f(g(x)))(u)).ap(Right(v)).ap(Right(w))  // Right#map
    = Right(v).map((f => g => x => f(g(x)))(u)).ap(Right(w))        // Right#ap
    = Right((f => g => x => f(g(x)))(u)(v)).ap(Right(w))            // Right#map
    = Right(w).map((f => g => x => f(g(x)))(u)(v))                  // Right#ap
    = Right((f => g => x => f(g(x)))(u)(v)(w))                      // Right#map
    = Right((g => x => u(g(x)))(v)(w))                              // apply `u`
    = Right((x => u(v(x)))(w))                                      // apply `v`
    = Right(u(v(w)))                                                // apply `w`

Right(u).ap(Right(v).ap(Right(w)))                                  // RHS
    = Right(v).ap(Right(w)).map(u)                                  // Right#map
    = Right(w).map(v).map(u)                                        // Right#ap
    = Right(v(w)).map(u)                                            // Right#map
    = Right(u(v(w)))                                                // Right#map
```

So it holds in almost every case. And knowing which case it fails in, you can show that it's unlawful with a simple example:

```coffee
coffee> Right((x) -> !x).map((f) -> (g) -> (x) -> f(g(x))).ap(Left('wat')).ap(Right(true))
_Right { value: true }
coffee> Right((x) -> !x).ap(Left('wat').ap(Right(true)))
_Right { value: false }
```

This is something a property based test would have caught eventually. How long? dunno, but not that many tests would have needed to run in order to prove there was a bug in there.

I'm not going to prove that the change works in all cases, someone else can do that, and it's a good way to learn about proofs.

**Comment by davidchambers** [comment]
This is very instructive, @joneshf! Thank you for taking the time to write this.

**Comment by scott-christopher** [comment]
I've raised #77 to address this.
