### ISSUE TITLE
shouldn't Left have a map?

### ISSUE THREAD

**Issue by reharik** [ramda/ramda-fantasy#80]
Shouldn't Left have a map that returns self?  
If I have an Either and I call map on it, I want it to Either do the mapping or if it's a Left than return the Either with the left in it. Don't I?
Thanks,
R

**Comment by davidchambers** [comment]
It certainly should. It appears to be [defined][1]:

> ```javascript
> Either.prototype.map = util.returnThis;
> ```


[1]: https://github.com/ramda/ramda-fantasy/blob/v0.4.1/src/Either.js#L19

**Comment by reharik** [comment]
so it is.  Sorry about that. I missed it.
Thanks,
Raif
