### ISSUE TITLE
name change?

### ISSUE THREAD

**Issue by buzzdecafe** [ramda/ramda-fantasy#99]
from this comment: https://github.com/ramda/ramda/issues/1638#issuecomment-183568161

anyone have strong feelings one way or the other on the name `ramda-fantasy`? Possible alternatives (in no particular order) include:

* ramda-types
* algebramda
* ramdalgebra
* ???

**Comment by CrossEye** [comment]
I would be strongly in favor of changing the name of FantasyLand (See https://github.com/fantasyland/fantasy-land/issues/92#issuecomment-118576261 for why.)  If that were to change (which doesn't seem likely), then "Ramda-Fantasy" would be a meaningless and odd name.  So I guess I'm in favor of changing it, but it's not something that excites me.

**Comment by scott-christopher** [comment]
I'm not too bothered by the current name, but `ramda-types` would be my preference from that list.

**Comment by arcseldon** [comment]
Would opt for either `ramda-types` or `algebramda` - think they are both descriptive and approachable.

**Comment by mattferrin** [comment]
I really like ```ramda-types```, but am only just a curious observer here.

**Comment by cowlike** [comment]
I'm a casual user of Ramda who is watching it closely. I like Ramda-types
but trying to combine Ramda and algebra just sounds very clumsy to me.

**Comment by buzzdecafe** [comment]
> trying to combine Ramda and algebra just sounds very clumsy to me.

:laughing:  me too -- i suggested it as a joke, but _three people said they liked it_. i think `ramda-types` may be clearer about the intent

**Comment by TheLudd** [comment]
I say keep the name for the sake of not over complicating things. If we were starting over perhaps another name would be chosen but the one we have is not bad. There is no such thing as a perfect descriptive name and I don't think the name has a big impact on how people approach it. After all, how descriptive of a name is "ramda"?

**Comment by arcseldon** [comment]
@TheLudd - interesting perspective. Just googled, and [this article](http://www.entrepreneur.com/article/76958) was first to pop up. Not saying this isn't a unbiased viewpoint by any means, but believe some of it might be accurate at least. 

> Naming a business is a lot like laying the cornerstone of a building. Once it's in place, the entire foundation and structure is aligned to that original stone. If it's off, even just a bit, the rest of the building is off, and the misalignment becomes amplified

Believe "Mistake #8: Choosing the wrong name and then refusing to change it" is worthy of consideration in that article as it relates to the use of the word 'fantasy". 

But all said and done, maybe you're right, and ramda-fantasy is good enough.

**Comment by TheLudd** [comment]
I don't buy that analogy =)

And this is not a business. It is a library, and at that a specialized one. It builds on ramda and implements types according to the fantasy-land specification. Is it the best name? Perhaps not. Is it bad? Definitely not.

**Comment by joneshf** [comment]
@arcseldon that article also gives this mistake

> Mistake #1: Getting the "committee" involved in your decision.

**Comment by cowlike** [comment]
Getting input from users is not the same thing as making a decision.

**Comment by buzzdecafe** [comment]
yeah, i feel like we can keep it as-is for the foreseeable future, so i think this is ok to close. Should there be a huge outcry then i'd be happy with the (admittedly, somewhat prosaic) `ramda-types`.
